name: "CI"

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_call:

jobs:
  lint:
    name: "Linting"
    runs-on: ubuntu-latest

    steps:
      - name: "Checkout"
        uses: actions/checkout@v2

      - name: "Setup NodeJS"
        uses: actions/setup-node@v2
        with:
          node-version: "16"

      - name: "Install dependencies"
        run: "npm install"

      - name: "Run prettier"
        run: "npm run prettier:check"
